# Generated by Django 2.2 on 2020-08-14 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_employeeinformation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ntteamleadinformation',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='ntteamleadinformation',
            name='team_address',
        ),
        migrations.RemoveField(
            model_name='ntteamleadinformation',
            name='team_landline',
        ),
        migrations.RemoveField(
            model_name='ntteamleadinformation',
            name='team_mobile',
        ),
        migrations.RemoveField(
            model_name='ntteamleadinformation',
            name='team_name',
        ),
        migrations.AddField(
            model_name='ntteamleadinformation',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='team', to='core.EmployeeInformation'),
            preserve_default=False,
        ),
    ]
