# Generated by Django 2.2 on 2020-08-14 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200814_1018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeinformation',
            old_name='team_added_on',
            new_name='added_on',
        ),
        migrations.RenameField(
            model_name='employeeinformation',
            old_name='team_updated_on',
            new_name='updated_on',
        ),
    ]
